using System;

namespace SOS.OrderTracking.Web.Portal.GBMS.Models
{
    public partial class StrfedbnD1
    {
        public int Stiseqno { get; set; }
        public int Stmseqno { get; set; }
        public string? Smitem { get; set; }
        public string? Ucode { get; set; }
        public decimal? Stiqty { get; set; }
        public string? Stiratetag { get; set; }
        public decimal? Stirate { get; set; }
        public decimal Stivalue { get; set; }
        public string Chaccode { get; set; } = null!;
        public string? Staccode { get; set; }
        public string? Stiremark { get; set; }
        public string? Lccodeto { get; set; }
        public decimal? Stidiscp { get; set; }
        public decimal? Stidisc { get; set; }
        public decimal? Stistaxp { get; set; }
        public decimal? Stistax { get; set; }
        public decimal? Stisedp { get; set; }
        public decimal? Stised { get; set; }
        public decimal? Stiitaxp { get; set; }
        public decimal? Stiitax { get; set; }
        public decimal? Stifreight { get; set; }
        public decimal? Stioctroi { get; set; }
        public decimal? Stiothr { get; set; }
        public decimal Stinetvalue { get; set; }
        public string? Stifl1 { get; set; }
        public string? Stifl2 { get; set; }
        public string? Stifl3 { get; set; }
        public string? Stifl4 { get; set; }
        public string? Stifl5 { get; set; }
        public string? Stifl6 { get; set; }
        public string? Stifl7 { get; set; }
        public string? Stifl8 { get; set; }
        public string? Stifl9 { get; set; }
        public string? Stifl10 { get; set; }
        public string? Stifl11 { get; set; }
        public string? Stifl12 { get; set; }
        public string? Stifl13 { get; set; }
        public string? Stifl14 { get; set; }
        public string? Stifl15 { get; set; }
        public string? Stifl16 { get; set; }
        public string? Stifl17 { get; set; }
        public string? Stifl18 { get; set; }
        public string? Stifl19 { get; set; }
        public string? Stifl20 { get; set; }
        public string? Stifl21 { get; set; }
        public string? Stifl22 { get; set; }
        public string? Stifl23 { get; set; }
        public string? Stifl24 { get; set; }
        public string? Stifl25 { get; set; }
        public string? Stifl26 { get; set; }
        public string? Stifl27 { get; set; }
        public string? Stifl28 { get; set; }
        public string? Stifl29 { get; set; }
        public string? Stifl30 { get; set; }
        public string? Stifl31 { get; set; }
        public string? Stifl32 { get; set; }
        public string? Stifl33 { get; set; }
        public string? Stifl34 { get; set; }
        public string? Stifl35 { get; set; }
        public string? Stifl36 { get; set; }
        public string? Stifl37 { get; set; }
        public string? Stifl38 { get; set; }
        public string? Stifl39 { get; set; }
        public string? Stifl40 { get; set; }
        public string? Stifl41 { get; set; }
        public string? Stifl42 { get; set; }
        public string? Stifl43 { get; set; }
        public string? Stifl44 { get; set; }
        public string? Stifl45 { get; set; }
        public string? Stifl46 { get; set; }
        public string? Stifl47 { get; set; }
        public string? Stifl48 { get; set; }
        public string? Stifl49 { get; set; }
        public string? Stifl50 { get; set; }
        public decimal? Stifln1 { get; set; }
        public decimal? Stifln2 { get; set; }
        public decimal? Stifln3 { get; set; }
        public decimal? Stifln4 { get; set; }
        public decimal? Stifln5 { get; set; }
        public decimal? Stifln6 { get; set; }
        public decimal? Stifln7 { get; set; }
        public decimal? Stifln8 { get; set; }
        public decimal? Stifln9 { get; set; }
        public decimal? Stifln10 { get; set; }
        public decimal? Stifln11 { get; set; }
        public decimal? Stifln12 { get; set; }
        public decimal? Stifln13 { get; set; }
        public decimal? Stifln14 { get; set; }
        public decimal? Stifln15 { get; set; }
        public decimal? Stifln16 { get; set; }
        public decimal? Stifln17 { get; set; }
        public decimal? Stifln18 { get; set; }
        public decimal? Stifln19 { get; set; }
        public decimal? Stifln20 { get; set; }
        public decimal? Stifln21 { get; set; }
        public decimal? Stifln22 { get; set; }
        public decimal? Stifln23 { get; set; }
        public decimal? Stifln24 { get; set; }
        public decimal? Stifln25 { get; set; }
        public DateTime? Stifld1 { get; set; }
        public DateTime? Stifld2 { get; set; }
        public DateTime? Stifld3 { get; set; }
        public DateTime? Stifld4 { get; set; }
        public DateTime? Stifld5 { get; set; }
        public DateTime? Stifld6 { get; set; }
        public DateTime? Stifld7 { get; set; }
        public DateTime? Stifld8 { get; set; }
        public DateTime? Stifld9 { get; set; }
        public DateTime? Stifld10 { get; set; }
        public DateTime? Stifld11 { get; set; }
        public DateTime? Stifld12 { get; set; }
        public DateTime? Stifld13 { get; set; }
        public DateTime? Stifld14 { get; set; }
        public DateTime? Stifld15 { get; set; }
        public string Sticd1 { get; set; } = null!;
        public string Sticd2 { get; set; } = null!;
        public string Sticd3 { get; set; } = null!;
        public string? Sticd4 { get; set; }
        public string? Sticd5 { get; set; }
        public string? Sticd6 { get; set; }
        public string? Sticd7 { get; set; }
        public string? Sticd8 { get; set; }
        public string? Sticd9 { get; set; }
        public string? Sticd10 { get; set; }
        public string? Sticd11 { get; set; }
        public string? Sticd12 { get; set; }
        public string? Sticd13 { get; set; }
        public string? Sticd14 { get; set; }
        public string? Sticd15 { get; set; }
        public string? Sticd16 { get; set; }
        public string? Sticd17 { get; set; }
        public string? Sticd18 { get; set; }
        public string? Sticd19 { get; set; }
        public string? Sticd20 { get; set; }
        public string? Sticd21 { get; set; }
        public string? Sticd22 { get; set; }
        public string? Sticd23 { get; set; }
        public string? Sticd24 { get; set; }
        public string? Sticd25 { get; set; }
        public string? UseridAdd { get; set; }
        public string? UseridModify { get; set; }
        public string? IpAdd { get; set; }
        public string? SysAdd { get; set; }
        public DateTime? AddDate { get; set; }
        public string? IpMod { get; set; }
        public string? SysMod { get; set; }
        public DateTime? ModDate { get; set; }
        public string? IdDel { get; set; }
        public string? IpDel { get; set; }
        public string? SysDel { get; set; }
        public DateTime? DelDate { get; set; }

        public virtual Strfedbn StmseqnoNavigation { get; set; } = null!;
    }
}
